// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Upnp.Control.DataAccess;

#nullable disable

namespace Upnp.Control.DataAccess.Migrations.PushSubscriptionDb
{
    [DbContext(typeof(PushSubscriptionDbContext))]
    [Migration("20220813102749_Upgrade_EF7")]
    partial class Upgrade_EF7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2");

            modelBuilder.Entity("Upnp.Control.Models.PushNotifications.PushNotificationSubscription", b =>
                {
                    b.Property<string>("Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AuthKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("P256dhKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Endpoint");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
