// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Upnp.Control.DataAccess;

#nullable disable

namespace Upnp.Control.DataAccess.Migrations.PushSubscriptionDb
{
    [DbContext(typeof(PushSubscriptionDbContext))]
    partial class PushSubscriptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0-rc.2.21480.5");

            modelBuilder.Entity("Upnp.Control.Models.PushNotificationSubscription", b =>
                {
                    b.Property<string>("Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AuthKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("P256dhKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Endpoint", "Type");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
