// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Upnp.Control.DataAccess.Migrations.PushSubscriptionDb
{
    [DbContext(typeof(PushSubscriptionDbContext))]
    partial class PushSubscriptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Upnp.Control.Models.PushNotifications.PushNotificationSubscription", b =>
                {
                    b.Property<string>("Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AuthKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("P256dhKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Endpoint");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}