// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Upnp.Control.DataAccess.Migrations.UpnpDb
{
    [DbContext(typeof(UpnpDbContext))]
    [Migration("20231120141209_Upgrade_EF8")]
    partial class Upgrade_EF8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Upnp.Control.Models.UpnpDevice", b =>
                {
                    b.Property<string>("Udn")
                        .HasColumnType("TEXT");

                    b.Property<string>("BootId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentationUri")
                        .HasColumnType("TEXT");

                    b.HasKey("Udn");

                    b.ToTable("UpnpDevices");
                });

            modelBuilder.Entity("Upnp.Control.Models.UpnpDevice", b =>
                {
                    b.OwnsMany("Upnp.Control.Models.Icon", "Icons", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Mime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Udn")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Url")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("Udn");

                            b1.ToTable("Icon");

                            b1.WithOwner()
                                .HasForeignKey("Udn");
                        });

                    b.OwnsMany("Upnp.Control.Models.Service", "Services", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ControlUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EventsUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MetadataUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ServiceType")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Udn")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("UniqueServiceName")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("Udn");

                            b1.ToTable("Service");

                            b1.WithOwner()
                                .HasForeignKey("Udn");
                        });

                    b.Navigation("Icons");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}