// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Upnp.Control.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Upnp.Control.DataAccess.CompiledModels
{
    public static class IconUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Height>k__BackingField")]
        public static extern ref int Height(Icon @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Mime>k__BackingField")]
        public static extern ref string Mime(Icon @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Url>k__BackingField")]
        public static extern ref Uri Url(Icon @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Width>k__BackingField")]
        public static extern ref int Width(Icon @this);
    }
}