// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Upnp.Control.DataAccess;
using Upnp.Control.DataAccess.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(PushSubscriptionDbContext), typeof(PushSubscriptionDbContextModel))]