// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Upnp.Control.Models.PushNotifications;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Upnp.Control.DataAccess.CompiledModels
{
    public static class PushNotificationSubscriptionUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Endpoint>k__BackingField")]
        public static extern ref Uri Endpoint(PushNotificationSubscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AuthKey>k__BackingField")]
        public static extern ref byte[] AuthKey(PushNotificationSubscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Created>k__BackingField")]
        public static extern ref DateTimeOffset Created(PushNotificationSubscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<P256dhKey>k__BackingField")]
        public static extern ref byte[] P256dhKey(PushNotificationSubscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
        public static extern ref NotificationType Type(PushNotificationSubscription @this);
    }
}