// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Upnp.Control.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Upnp.Control.DataAccess.CompiledModels
{
    public static class ServiceUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ControlUrl>k__BackingField")]
        public static extern ref Uri ControlUrl(Service @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EventsUrl>k__BackingField")]
        public static extern ref Uri EventsUrl(Service @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MetadataUrl>k__BackingField")]
        public static extern ref Uri MetadataUrl(Service @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ServiceType>k__BackingField")]
        public static extern ref string ServiceType(Service @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UniqueServiceName>k__BackingField")]
        public static extern ref string UniqueServiceName(Service @this);
    }
}