// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Upnp.Control.DataAccess.CompiledModels
{
    [DbContext(typeof(UpnpDbContext))]
    public partial class UpnpDbContextModel : RuntimeModel
    {
        static UpnpDbContextModel()
        {
            var model = new UpnpDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static UpnpDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
