// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Upnp.Control.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Upnp.Control.DataAccess.CompiledModels
{
    public static class UpnpDeviceUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Udn>k__BackingField")]
        public static extern ref string Udn(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BootId>k__BackingField")]
        public static extern ref string BootId(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ConfigId>k__BackingField")]
        public static extern ref string ConfigId(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DeviceType>k__BackingField")]
        public static extern ref string DeviceType(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpiresAt>k__BackingField")]
        public static extern ref DateTime ExpiresAt(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FriendlyName>k__BackingField")]
        public static extern ref string FriendlyName(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Location>k__BackingField")]
        public static extern ref Uri Location(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Manufacturer>k__BackingField")]
        public static extern ref string Manufacturer(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ManufacturerUri>k__BackingField")]
        public static extern ref Uri ManufacturerUri(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelName>k__BackingField")]
        public static extern ref string ModelName(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelNumber>k__BackingField")]
        public static extern ref string ModelNumber(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelUri>k__BackingField")]
        public static extern ref Uri ModelUri(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PresentationUri>k__BackingField")]
        public static extern ref Uri PresentationUri(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Icons>k__BackingField")]
        public static extern ref IEnumerable<Icon> Icons(UpnpDevice @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Services>k__BackingField")]
        public static extern ref IEnumerable<Service> Services(UpnpDevice @this);
    }
}