// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Web.Upnp.Control.DataAccess.CompiledModels
{
    [DbContext(typeof(PushSubscriptionDbContext))]
    public partial class PushSubscriptionDbContextModel : RuntimeModel
    {
        static PushSubscriptionDbContextModel()
        {
            var model = new PushSubscriptionDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static PushSubscriptionDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
