ARG distro=alpine-arm64v8
FROM mcr.microsoft.com/dotnet/runtime-deps:5.0-${distro} AS final

RUN adduser -u 5678 --disabled-password --home /app --gecos "" upnp-dashboard && chown -R upnp-dashboard /app
USER upnp-dashboard

WORKDIR /app
COPY . .

EXPOSE 8080
EXPOSE 8081

ENTRYPOINT ["./Web.Upnp.Control"]
